---
- name: cacti_server sys265
  hosts: cacti_server
  become: true
  vars:
      install_utilities: false
      firewalld_disable: true
  roles:
  - Oefenweb.cacti_server

  tasks:
  - name: add firewall rule
    firewalld:
      port: 10000/tcp
      permanent: true
      state: enabled
